### ISSUE TITLE
Fix bitwise operator monoid names

### ISSUE THREAD

**Issue by mcordery** [DrTimothyAldenDavis/GraphBLAS#164]
I would suggest making a minor change to make the bitwise operator monoid names self consistent with the rest. As it is the other monoids have the suffix _MONOID_TYPE, whereas the bitwise operators have the suffix _TYPE_MONOID (the old convention).

**Comment by DrTimothyAldenDavis** [comment]
That would be a good idea but it's too disruptive (it would break older codes).

I had defined monoids before they were in the spec at all, and i used the convection GxB_op_type_MONOID.  If a name is GxB then it's my own naming scheme.  Then the C API committee added monoids, and named them GrB_op_MONOID_type.  All future GrB monoids will have that definition.  I don't control the C API, although I do provide them with input.

It would be nice if the names were GxB_op_MONOID_type, but it's too late to change those.  Hopefully the will get added to the C API, and when that happens they will have the names GrB_op_MONOID_type.

**Comment by DrTimothyAldenDavis** [comment]
I could add aliases, so that GxB_BAND_MONOID_UINT8 and GxB_BAND_UINT8_MONOID would point to the same object, but that would be quite a lot of new names in the symbol table, particularly if I did it for all of my GxB semirings, which have a different name format as the GrB semirings.

Perhaps a #define could be done ... it wouldn't cause a symbol table bloat.

**Comment by mcordery** [comment]
It's not a big deal, just pointed it out for the sake of self-consistency

**Comment by DrTimothyAldenDavis** [comment]
Yes, it's inconsistent but something that would be tricky to fix...
