### ISSUE TITLE
GRB_VERSION / GrB_SUBVERSION

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#17]
On page 45 of "GraphBLAS_API_C_v13.pdf", I see:
```C
#define GRB_VERSION     1
#define GrB_SUBVERSION  3
```
I am surprised by the use of `GRB` (all caps), and also the inconsistency (`GRB` and `GrB`).  Do you know whether these should both be `GRB` (as you define them in your header file), or `GrB`?  I know this is more of a GraphBLAS question, but I wasn't sure where else to ask.

**Comment by DrTimothyAldenDavis** [comment]
That's a typo in the v1.3 C API.  It's fixed in the latest version of the C
API, and SuiteSparse:GraphBLAS uses the corrected version:  GRB_VERSION and
GRB_SUBVERSION.

Yes, I would prefer the GrB_VERSION and GrB_SUBVERSION, but the C API
committee went with GRB, not GrB.  This is the only instance of the GRB
(all caps) prefix in the API.  I think the reasoning is that this is the
only place where the library must define a C macro, with a #define.  All
other constants are enums and such.  So they used all caps for the names of
the 2 macros.

**Comment by eriknw** [comment]
Okay, thanks for the explanation!
