### ISSUE TITLE
Sparse Index Space

### ISSUE THREAD

**Issue by victorstewart** [DrTimothyAldenDavis/GraphBLAS#176]
currently i generate a static graph index for each entity, which requires routing through a singular database instance to ensure sequence, but i devised a way in my mind to break this dependency and generate unique indexes in a decentralized manner, but my question is... say graphs and vector were sized to the entire uint64_t number space, but only 0.000000010842% of that space were every occupied at terminal saturation and usually orders of magnitude less... would there still be a huge memory cost to be paid?

i know i could check this with a test program quickly but i figured in the case it would exhaust memory maybe there's a solution.

**Comment by DrTimothyAldenDavis** [comment]
That would work just fine because of my hypersparse format. The only
constraint is that the biggest matrix you can create is 2^60 by 2^60.  I
can’t do 2^64 because I need a few bits for zombies and such.

The memory footprint of a hypersparse matrix is O (nvals(A)).  The
dimensions don’t matter.
-- 
Sent from Gmail Mobile

**Comment by victorstewart** [comment]
so the maximum value is 2^60 -1. perfect!
