### ISSUE TITLE
make static not working as expected in 9.0.1 release

### ISSUE THREAD

**Issue by AviAvni** [DrTimothyAldenDavis/GraphBLAS#271]
not able to compile static lib in 9.0.1 version

**Comment by DrTimothyAldenDavis** [comment]
Sorry for the mishap.  The feature was revised in the cmake scripts.  It is still there but the Makefile wasn't updated correctly to make the change in the cmake scripts.  Instead of -DNSTATIC=0 in the Makefile (the cmake option, in "make static") you need `-DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF`.  I'll update the Makefile and post a version 9.0.2.

In the mean time, you can use

```
cd build
cmake  -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF .. 
cmake --build . --config Release 
```

**Comment by DrTimothyAldenDavis** [comment]
See https://github.com/DrTimothyAldenDavis/GraphBLAS/tree/v9.0.0.branch with version 9.0.2.  I'll release it later today.

**Comment by DrTimothyAldenDavis** [comment]
Posted as v9.0.2.beta1.  Let me know if it works for you and I'll post it as the stable v9.0.2.

 https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v9.0.2.beta1

**Comment by AviAvni** [comment]
yes it is working thank you very much
