### ISSUE TITLE
GrB_MINUS_REMOVE

### ISSUE THREAD

**Issue by victorstewart** [DrTimothyAldenDavis/GraphBLAS#30]
I've got a situation where I'm extracting vectors and then adding or subtracting them to another column or row using `GxB_Col_subassign` and `GxB_Row_subassign` with `GrB_PLUS_UINT16` and `GrB_MINUS_UINT16`. 

the problem is when an entry becomes 0 after subtracting and should be removed... currently the only way I see to do this would be iteratively checking every entry after each subtraction operation, which i'm very weary of given extreme outliers might arise in my application on the order of many thousands (hopefully millions) of entries. but maybe such concerns are moot given each value would have to iteratively touched inside the library anyway, and they aren't operated on in some SIMD-esque way? 

in either case, ideally there would be a `GrB_MINUS_REMOVE_UINT16` operator that removed any value that hit zero... regardless of iteration or not, only requiring the data to be visited and operated on once. but i'm not sure how beyond the pale that is currently?

i considered the idea of a `GrB_Col_extract` that let me filter for 0 values and then iterate over them, but I assume inside the library all the entries would still have to be visited iteratively to test their values equal 0?

maybe you have another idea of how to best accomplish this?

worst case i might decide to just leave them as zombie zeros since they would not interfere with the operation of my database, just simply consume excess memory.

**Comment by DrTimothyAldenDavis** [comment]
I understand what you are trying to do, but a MINUS_REMOVE operator
wouldn't be the way to do it.

It would be really difficult, and it would cause confusion in the API, if
there was such a binary operator GrB_MINIUS_REMOVE.  It would be a
disruptive change to eWiseAdd and eWiseMult, since currently the structure
of the result of these methods do not depend on the operator.  And if there
is a MINUS_REMOVE, shouldn't there also be PLUS_REMOVE?  And what should be
removed, just zeros?  Zeros are not special in GraphBLAS.  Also, what does
GrB_MINUS_REMOVE mean if used as the multiplicative operator in a
semiring?  It would break the meaning of GrB_mxm.  And finally, GrB_assugn
and GxB_subassign are already insanely complicated to implement, and this
would just add far too much additional complexity to be considered.  There
are way too many problems with considering such an operator, so there's
really no way to add this as a binary operator.

The best way to handle this is to compute your result, and then use
GxB_select to remove zeros, using the GxB_NONZERO operator, as the
GxB_SelectOp.  This is well-defined.  It's an extension to the GraphBLAS
API, but one that is being considered for inclusion in the GraphBLAS C API
since this kind of select problem, or "functional mask" comes up so often.
The GxB_select operation also fits nicely with all of the other GraphBLAS
operations.  It's not disruptive, unlike a "MINUS_REMOVE" operator.
