### ISSUE TITLE
Please don't deprecate GxB_EQ_BOOL_MONOID

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#31]
It appears that you list this as being deprecated in your header file.  I prefer the name `GxB_EQ_BOOL_MONOID` over `GrB_LXNOR_MONOID_BOOL`.

I see that you chose to have `EQ_{EQ,NE,GT,LT,GE,LE,...}` semirings instead of `LXNOR_{...}`.  If you have semirings that use `EQ` for a monoid, then it's reasonable to expect to have `EQ` monoids as well.

Similarly, it appears that the `GxB_EQ_LOR_BOOL` semiring is deprecated in favor of `GrB_LXNOR_LOR_SEMIRING_BOOL`.  It would be nice to keep the original name around.

If you choose not to deprecate these, please highlight this fact in the header file (perhaps you already have a blanket statement like "`EQ` is always preferred over `LXNOR` and won't be deprecated", but I may have missed this).

**Comment by DrTimothyAldenDavis** [comment]
I don't plan on removing the GxB* names any time soon, if ever.  I think at
most I would simply quietly
remove them from the documentation, but keep them in GraphBLAS.h and in the
library itself, and tag
them as "historical" rather than "deprecated".  So they would still work,
going forward.  Removing them
entirely is something I'd only do after getting substantial feedback about
it.

For semirings, the spec added only 124 predefined GrB* semirings, and I
have many more.
It would be confusing to everyone (me, and any users) if I were to remove
the 124 corresponding GxB* semirings while at
the same time keeping the other 1,553-124 = 1,428 GxB* semiring names.  So
I'll need to keep all my GxB* semirings
for a long while.

Maybe if the spec catches up, and adds all 1,553 semirings, then I could
consider actually removing my GxB* semirings.
Even then, I think it would be reasonable to keep all my GxB* semirings as
"historical" (that is, not documented,
but kept in GraphBLAS.h in working order).

If possible, the GrB* names and functions should be used instead, when the
spec catches up with SuiteSparse.

The GrB_EQ_BOOL operator is in the spec, and
predates the GrB_LXNOR, which is the same operator with a different name.
The LXNOR was added
later to the spec, and I haven't changed my GxB* names (or added ones) to
match the LXNOR naming scheme.

That's why you see a mix of names, with EQ_BOOL and LXNOR.  Yes, I can
understand a preference for one over
the other.  I see pros and cons of both names (EQ is simpler, but its name
hides the fact that it is closely
related to the LXOR operator).  The spec has kept GrB_EQ_BOOL, alongside
the new GrB_LXNOR,
even though the two operators are identical.  So I think the best thing is
to keep both names.

**Comment by eriknw** [comment]
Thanks for clarifying your policy on these names.  This works for me.  Closing.

**Comment by DrTimothyAldenDavis** [comment]
I've replaced the term "deprecated" with "historical" for all but the no-input GrB_wait (which had to be removed since it conflicts with the 1-input GrB_wait in the spec).  See the GraphBLAS.h where I describe what I mean by "historical".

**Comment by DrTimothyAldenDavis** [comment]
I've also added a section in the User Guide about historical vs deprecated, at the end of Section 1.1, Release Notes.
