### ISSUE TITLE
`GrB_Matrix_wait (A, GrB_MATERIALIZE)` not computing HyperHash

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#363]
I had a test in Python for `GxB_unpack_HyperHash` (and pack) that works for SuiteSparse:GraphBLAS 8.2.1, but fails for 9.3.1. In particular, I have a hypersparse matrix (hypercsr), and I call `GrB_Matrix_wait (A, GrB_MATERIALIZE)` on it, which the documentation says will compute the hyperhash. However, when I call `GxB_unpack_HyperHash` after calling `wait` (same result when using "materialize" or "complete"), I get back `NULL` indicating the hyperhash was not computed. Introspection of the matrix shows it to be in hypersparse format.

**Comment by DrTimothyAldenDavis** [comment]
I changed my data structure so that not all hypersparse matrices need the hyper-hash.  I only build it if the matrix has more than some threshold of non-empty vectors.  This was because building the hyperhash when the matrix had very few non-empty vectors slows things down. (In FalkorDB in particular: @swilly22 ).  

The hyper-hash is optional; if I don't have it I do the work without it.  Returning NULL from unpack_HyperHash is not an error condition.

**Comment by eriknw** [comment]
Okay, thanks for the explanation! The docs made it sound like it _will_ calculate the hyper-hash, not _may_, so either I misread somewhere or the docs could maybe be updated.

Closing.

**Comment by DrTimothyAldenDavis** [comment]
Got it.. I'll fix my Docs.

**Comment by DrTimothyAldenDavis** [comment]
See https://github.com/DrTimothyAldenDavis/GraphBLAS/commit/7bfe96eef350453bb78a0bb4dba14ff021115664
