### ISSUE TITLE
Transpose mask

### ISSUE THREAD

**Issue by zawadisvela** [DrTimothyAldenDavis/GraphBLAS#46]
Is it possible to transpose the mask in a GraphBLAS operation?

**Comment by DrTimothyAldenDavis** [comment]
No, unfortunately.  The C API doesn't provide for a transposed mask descriptor.  I do have to handle the case anyway, because of my data formats.  Say you're doing an assign with C<M>=A, and suppose C and A are CSR but M is CSC.  Then I have to transpose the mask, even though there's no descriptor for it (you can see this by grepping the code for the token "M_transpose".  But there is no C API mechanism to provide me with this information.

**Comment by zawadisvela** [comment]
Okay, thank you.
