### ISSUE TITLE
Extract matrix values (edges) used in a VxM

### ISSUE THREAD

**Issue by zawadisvela** [DrTimothyAldenDavis/GraphBLAS#47]
Is there any easy way to produce a matrix consisting only of the values interacted with in a VxM operation? 

Specifically, I am using one step of a breadth-first search-like procedure to produce an s-t cut in the graph. I know that the edges traversed in this VxM corresponds to the cut I need, but I am unsure how to extract them. 

The VxM produces the full set of vertices on the "t-side" of the cut, and by searching one step "backwards" again (VxM with using the t-set and the tranposed graph) I could produce *all* the parent-vertices. By taking all the edges then implicitly stored in the two sets of vertices, I would likely get most but not all of the cut. 

I could also utilize these two sets of vertices to find the edges manuallly using matrix_extract, but that would lead to the kind of run-time I am trying to avoid.

I would appreciate any help, or an indication that this kind of procedure isn't really supported in GraphBLAS.

**Comment by DrTimothyAldenDavis** [comment]
I'm not sure I understand your question.  Can you give me an example?

**Comment by zawadisvela** [comment]
Practically, I have run an s-t max-flow algorithm on a graph and produced the residual graph R, and I am trying to efficiently find the min-cut.

Performing a breadth-first search from the source s in R, I can determine all vertices reachable from the source, the **s**-set. 

![graph_example](https://user-images.githubusercontent.com/21154137/121172097-9efca700-c857-11eb-99e0-b248f243ceff.jpg)
A picture of an example graph **G.** The marked edges are the min-cut edges I want to extract. Those, along with other edges used at full capacity in the max-flow algorithm would not be in **R**, which is why a breadth-first search starting from the source-vertex on the left would produce **s**.

In order to find the vertices at the **t**-side of the cut, I can perform a single VxM operation  **t**<**s**'> = **s** * **G**, where **G** is the original graph input. What I think I am doing here is using the aquired **s** as frontier and traversing outward from it into the graph, but ignoring any vertices already present in **s** by using the mask.

In this last VxM operation, the "traversed edges" are the ones I wan to extract, which is why I asked if there is some way of inspecting which matrix-values are actually used in a VxM operation. 

My current method for extracting the min-cut is simply iterating over all the vertex pairs (i,j), i in **s**, j in **t** and seeing if there is an edge (i,j) in the graph. Becaue this method has a time complexity of O(n^2), it doesn't quite cut it.

**Comment by victorstewart** [comment]
call the first node on the left A and then last node on the right B.

on the s side, do the multiplication forward twice to find all 2 degrees nodes from A.

then on the t side when you do the multiplication backwards from B (aka by the transpose of the edge matrix), simply mask the output of that multiplication by the edges reached in the 1st operation.

this gives you the intersection.

**Comment by DrTimothyAldenDavis** [comment]
It's still not clear to me what you want from the computation.  You've
marked those edges, but what do you want from them?  Do you want a list of
6 edges?  If so, do you want (i,j) pairs or just i or j?  Do you want the
number 6?  Do you want the numbers 2, 3, 1, which is the # of parents of
each node in t?

**Comment by victorstewart** [comment]
@DrTimothyAldenDavis  i think the point is that they start with the 2 distant nodes, and the assumption there exists one or more 3rd degree mappings between them, and want to extract all nodes that participate in that mapping.

**Comment by DrTimothyAldenDavis** [comment]
You can't extract internal values from inside the mxv or vxm, but there are
many other things you can do.  It depends on what is needed.  I can do all
of these in another call to various GrB methods:

(1) list of the 6 edges, as (i,j) pairs or (i,j,x) triplets.  Don't use 6
calls to GrB_extractElement; that would be slow.  use a single call to
GrB_extract to get them all with one integer index list being the list of
parents in s and the other integer index list the frontier of t.
(2) the 6 integers in the list i of (1)
(3) the 6 integers in the list j of (1)
(4) the # of children each node in the left has, with values 1,2,1,2, as a
sparse vector where x(v)=2 if node v is the 2nd node in the frontier of s
(it would be helpful if the diagram had node ids on it).
(5) the values 2,3,1, which a sparse vector x where x(v) = 3 if node v in
the set t has 3 parents in the set s.

**Comment by zawadisvela** [comment]
Sorry for being unclear. What I want is indeed the (1) alternative you presented here, a list of 6 edges as (i,j,x) triplets.

To use GrB_extract, it seems I need the (i,j) tuples already available in the form of row_indices and col_indices vectors. The problem for me then is constructing these two vectors.

**Comment by DrTimothyAldenDavis** [comment]
In particular, say t is the set of nodes in the frontier as you've drawn
them.  I'm unsure what s means, since it includes the source node in your
drawing, which is not a parent of any node in t.  So say s is the set of
parents of t.

s and t are both GrB_vectors.  Let si be the list of row indices of s, from
a GrB_extractTuples on s.  Let ti be the list of row indices from t.  In
this case, si has length 4 and ti has length 3.

Then use a single call to GrB_extract (C, ... A, si, 4, ti, 3, ....)  or
perhaps swap si and ti if I have it backwards.  The matrix C of size 4-by-3
has all 6 of the edges you want, and nothing else.

Then, if you want the list of edges in C itself, you can do
GrB_extractTuples on C to get them.

This process doesn't require any looping over these entries.  What you
don't want is a pair of nested for loops, like this:

for (k1 = 0 ; k1 < 4 ; k1++)
    i = si (k1)
    for (k2 = 0 ; k2 < 3 ; k2++)
         j = ti (k2)
         GrB_extractElement (..., A, i, j)

that would be exceedingly slow.

**Comment by DrTimothyAldenDavis** [comment]
Got it.  that's clear now.

You have the GrB_Vectors s and t already, right?  If so, then you can get
the indices with GrB_extractTuples.  You can also get them still faster
with GxB_*_export_CSC, but that is not a pure GrB* method.  The
import/export are also destructive; the export of s destroys s and you have
the list of indices si and values sx, exported from s.  You can rebuild s
from si and sx with the import, if you like.

**Comment by zawadisvela** [comment]
Got it to work. Below I am assuming **s** contains _only_ the vertices adjacent to the cut, not the somewhat confusing s-set I drew earlier. The process I ended up going for:
1. GrB_extractTuples on **s** and **t**
2. GrB_extract on **A** using the indices from 1., constructing a new matrix **C**
3. GrB_extractTuples on **C**
4. Translate the indices in 3. back to indices in the original matrix **A** by re-using the indices from 1.
     Note: This is just a sequential for-loop over the arrays
5. Construct a new matrix using the values from 3. and the translated indices from 4.

Ideally there could have been a way to use **s**  and **t** to perform a kind of extract/filter/mask on the orignal matrix while keeping its structure intact, which would have reduced this process to a single step. But, this worked, and saved me a whole lot of time compared to calling GrB_extractElement n^2 times 😅

**Comment by DrTimothyAldenDavis** [comment]
Great!

That sounds like a good solution.  It does bring up a few useful ways that
GraphBLAS could be extended.  In particular, I've wondered what it would
look like if the GrB_Index * arrays that are provided as inputs to
GrB_extract and GrB_assign might also be GrB_Vectors.  Here, you want to
use the row indices extracted from s and t.  I can also see the need to use
the values from vectors like s and t, to use as index inputs to GrB_extract
and GrB_assign.  This wouldn't be much faster than what you're doing now,
but it would be simpler.

For (4), it might also be possible to use GrB_assign, to compute your new
matrix S, say, as S(I,J) = C.  That step would do the index computation for
you, although assign is difficult to implement because it's such a powerful
operation, and there are cases where a simple loop like what you can do is
faster.

**Comment by zawadisvela** [comment]
When you say assign is a powerful (and I assume heavy) operation, does that mean other GraphBLAS functions might be faster even if assign is the most "intuitive"?

Specifially, in one part of my program I need to extract the elements in a matrix corresponding to a boolean mask. I can either do this using an um-masked element-wise multiplication or a masked assign.

Similarly when assigning one value to all the exisiting elements in a matrix, I can either perform a masked assign or an un-masked apply (by providing a unary function that always returns the same value).

In these cases, assign seems most intuitive, but I am unsure if it implies the best performance.

**Comment by DrTimothyAldenDavis** [comment]
Assign is powerful because it has the C(I,J)=A option, with any indices I
and J.
There are about 40 internal algorithms I have written for all the different
cases of the assign,
and some of them are slower than others because of the "(I,J)" part.  But
some of the assign
algorithms are very very fast, just as fast as (say), eWiseMult.  It's hard
to say for any given case.

For assigning a single value to all existing elements in a matrix, then
GrB_assign will be fastest, at least in v5.1.
It will take O(1) time and memory, regardless of the # of entries in the
matrix.  See my draft userguide in the master branch,
on the new "iso matrix" property.  The assignment C<C,struct>=pi uses C as
its own structural mask, and sets all
existing entries to pi (or whatever value you want).  The unmasked apply
with the ONE operator will do this too,
in O(1) time and memory, but only to set the values to 1.  If you have a
user-defined unary op, I can't tell that you
are constructing an "iso-valued" matrix, so this will be much much slower.

For extracting elements of a matrix to create a boolean mask ... it
depends.  Likely a masked assign is
fastest, or at least about the same as the eWiseMult.  It's hard to say
without know more details.
You can try turning on the burble to see what it does.  However, all this
will change in v5.1 where some cases
of assign, and many other operations, will drop drastically in run time and
memory usage, from O(nvals(C)) to
just O(1).
