### ISSUE TITLE
How to introspect a Vector or Matrix to determine if it's iso-valued

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#52]
Is there some way to ask a Vector or Matrix whether or not it's iso-valued?  Thanks.

**Comment by DrTimothyAldenDavis** [comment]
Good question.  The only way to do that currently is to print the vector or matrix (level 1 is sufficient) and look at the output.  I print the term "iso value: 1" if the matrix/vector is iso valued with an iso value of 1.

**Comment by DrTimothyAldenDavis** [comment]
It would be a good idea for me to provide a way to query a matrix or vector to see if it's iso-valued.  I can add that pretty easily.

**Comment by DrTimothyAldenDavis** [comment]
Added GxB_Matrix_iso and GxB_Vector_iso to v5.1.3.

**Comment by eriknw** [comment]
Relatedly, given an iso-valued Vector or Matrix, what's the best way to get the iso-value?  Reduce to scalar with the ANY Monoid?

**Comment by DrTimothyAldenDavis** [comment]
Yes, that would take just O(log(e)) time if the matrix has e entries.  It
could be done in O(1) time, of course, for
the ANY monoid.  That time is what it would be for all monoids (PLUS,
TIMES, MIN, MAX, etc).
Some monoids could be done in O(1) time (MIN, MAX, ANY, LOR, etc), but I
don't have the check for the special cases yet to do it
in O(1) instead of O(log (e)).  Even if the matrix has 2^120 entries, it
takes just 0.00017 seconds or so.
